###Add facing playbook with included role:

---
- hosts: #Add Host IP #localhost
  connection: local
  gather_facts: true
  become: yes

# Optional Vars are located in directory ansible-role-libvirt-vm/defaults/main.yml      
  vars:
##    cis_target_os_distribution: "RedHat" ### Example Var 
    libvirt_vm_default_console_log_dir: "/var/log/libvirt-consoles/"

    # The default location for libvirt images
    libvirt_volume_default_images_path: '/kvm-storage/images' ###'/var/lib/libvirt/images'

    # Default type for Libvirt volumes
    libvirt_volume_default_type: volume

    # The default format for Libvirt volumes.
    libvirt_volume_default_format: qcow2

    # The default device for Libvirt volumes.
    libvirt_volume_default_device: disk

    # Path to cache downloaded images.
    libvirt_vm_image_cache_path: "{{ libvirt_image_cache_path }}"
    
    # CPU architecture.
    libvirt_vm_arch: x86_64



    
  roles:
    - Kvm_vm_build
    
############Example_Of_New_Role##########
#---
#- hosts: webservers
#  gather_facts: true
#  tasks:
#    - include_role:
#        name: some_role
#      when: "ansible_facts['os_family'] == 'RedHat'"
#- name: talk to all hosts just so we can learn about them
#  hosts: all	      
#  tasks:	   
#    - name: Classify hosts depending on their OS distribution
#      group_by: 	        
#        key: os_{{ ansible_facts['distribution'] }}
