---
      
#- name: talk to all hosts just so we can learn about them
#  hosts: all	      
#  tasks:	   
#    - name: Classify hosts depending on their OS distribution
#      group_by: 	        
#        key: os_{{ ansible_facts['distribution'] }}
        
        
- hosts: webservers
  gather_facts: true
  tasks:
    - include_role:
        name: some_role
      when: "ansible_facts['os_family'] == 'RedHat'"
